version: "3.4"

services:
  redis:
    image: redis
    expose:
      - 6379
  flask-demo:
    env_file: .env
    build:
      context: ./flask-demo
      dockerfile: flask-demo.Dockerfile
    volumes:
      - ./flask-demo/app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '5000:5000'
  worker:
    build:
      context: ./flask-demo
      dockerfile: worker.Dockerfile
    volumes:
      - ./flask-demo/app:/app
    depends_on:
      - redis
    env_file:
      - ".env"
